blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/KoPyae2/screen-shoot-app/discussions
    about: Ask questions and discuss ideas with the community
